import asyncio
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field
from dotenv import load_dotenv
import os

load_dotenv()

class SentimentState(BaseModel):
    brand: str = Field("", description="The brand being analyzed")
    research_summary: str = Field("", description="Output from the Research Agent")
    monitoring_data: str = Field("", description="Output from the Social Media Monitor")
    sentiment_analysis: str = Field("", description="Output from the Sentiment Analyzer")
    report: str = Field("", description="Report generated by the Report Generator")
    final_output: str = Field("", description="The final aggregated output")

def initialize(state: SentimentState) -> SentimentState:
    state.brand = "FPT Telecom"
    print("Initialized brand:", state.brand)
    return state

def research_node(state: SentimentState) -> SentimentState:
    state.research_summary = f"Research data on {state.brand}."
    print("Research done.")
    return state

def monitor_node(state: SentimentState) -> SentimentState:
    state.monitoring_data = f"Monitoring metrics for {state.brand}."
    print("Monitoring done.")
    return state

def sentiment_node(state: SentimentState) -> SentimentState:
    state.sentiment_analysis = f"Sentiment for {state.brand}: Positive overall."
    print("Sentiment analysis done.")
    return state

def report_node(state: SentimentState) -> SentimentState:
    state.report = (
        f"Final Report:\n"
        f"Research: {state.research_summary}\n"
        f"Monitoring: {state.monitoring_data}\n"
        f"Sentiment: {state.sentiment_analysis}"
    )
    print("Report generated.")
    return state

def final_node(state: SentimentState) -> SentimentState:
    state.final_output = state.report + "\nAdditional recommendations."
    print("Final output prepared.")
    return state

# 1) Build the StateGraph
from langgraph.graph import StateGraph

graph = StateGraph(SentimentState)
graph.add_node("node_initialize", initialize)
graph.add_node("node_research", research_node)
graph.add_node("node_monitor", monitor_node)
graph.add_node("node_sentiment", sentiment_node)
graph.add_node("node_report", report_node)
graph.add_node("node_final", final_node)

graph.set_entry_point("node_initialize")
graph.add_edge("node_initialize", "node_research")
graph.add_edge("node_research", "node_monitor")
graph.add_edge("node_monitor", "node_sentiment")
graph.add_edge("node_sentiment", "node_report")
graph.add_edge("node_report", "node_final")
graph.add_edge("node_final", END)

app = graph.compile()

if __name__ == "__main__":
    # Option A: Some versions have a method like 'process' or 'evaluate'.
    # final_state = app.process(SentimentState())

    # Option B: If the library has an async method:
    # final_state = asyncio.run(app.kickoff_async(SentimentState()))

    # Option C: If it’s a direct call:
    # final_state = app(SentimentState())

    # Option D: If it has a method like 'run_flow' or 'execute_flow':
    # final_state = app.run_flow(SentimentState())

    # Last resort: we can try a catch-all approach:
    try:
        final_state = app.process(SentimentState())  # Example fallback
        print("\n----- Final Aggregated Output -----")
        print(final_state.final_output)
    except AttributeError as e:
        print("No 'process' method found. Check your library doc. Error:", e)
    except Exception as ex:
        print("Some other error occurred:", ex)
